config/routes.rb
Rails.application.routes.draw do

  root "searches#index"

  get "fetch_more", to: "searches#fetch_more"

  resources :searches, only: :create
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/search.rb
class Search < ApplicationRecord

  # params is for advanced search feature.
  validates :keywords, presence: true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :find_items, only: [:index, :fetch_more]

  def index
    @search = Search.new(keywords: @search.try(:keywords))
  end

  def create
    @search = Search.new(search_params)
    if @search.save
      redirect_to root_path(id: @search.id)
    else
      redirect_to root_path
    end
  end

  private
  def search_params
    params.require(:search).permit(:keywords)
  end

  def find_items
    if @search = Search.find_by(id: params[:id])
      flickr_search = Flickr::Search.new(text: @search.keywords, per_page: 100, page: params[:page] || 1)
    else
      flickr_search = Flickr::Recent.new(per_page: 100, page: params[:page] || 1)
    end
    @items = flickr_search.items
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photoship</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>

  <body>
    <div class="container-flux">
      <%= yield %>
    </div>
    <div class="loading"><center><%= image_tag('loading.gif')%></center></div>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/searches/_photo.html.erb
<figure>
  <%= link_to image_tag(photo[:url]), photo[:target], target: "_blank" %>
  <figcaption>
    <%= photo[:title] %>
  </figcaption>
</figure>

app/views/searches/fetch_more.js.erb
$("#photos").append("<%= escape_javascript(render partial: 'photo', collection: @items) %>");
$("#photos").data("links", "/fetch_more?page=<%= params[:page].to_i + 1 %>&id=<%= params[:id] %>");
$('.loading').hide();

app/views/searches/index.html.erb
<div class="row">
  <div class="col-md-11 col-md-offset-1">
    <%= simple_form_for @search, url: searches_path, html: { class: 'form-horizontal navbar-form' } do |f| %>
      <div class="input-group input-group-lg col-lg-12">
        <%= f.text_field :keywords, class: 'form-control input-lg', placeholder: "Input anywords to search, or leave blank to fetch recent flickr photos" %>
        <div class="input-group-btn">
          <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
        </div>
      </div>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="clearfix" id="photos" data-links="<%= "/fetch_more?page=2&id=#{params[:id]}" %>">
    <%= render partial: "photo", collection: @items %>
  </div>
</div>